Repository AY2425S2-CS2103T-T09-3/tp, pull requests merged in 2025-04, with the labels that each got.

#180 Change parameter check for Duplicate Handling
  src/main/java/seedu/address/model/reservation/Reservation.java
Labels: severity.Medium, alpha-bug

#185 Fix `Add` command remark detection
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, alpha-bug

#177 Update DG
  docs/DeveloperGuide.md
Labels: priority.Low

#165 Update Edit Command Test
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium

#191 Update mark and unmark command message
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
Labels: alpha-bug

#172 Fix Remark Message
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: severity.Low

#190 Add `findn` test cases
  src/test/java/seedu/address/logic/commands/FindByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByNameCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindByTimeCommandParserTest.java
  src/test/java/seedu/address/model/reservation/TimeMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
Labels: priority.Medium

#189 Add `findt` test cases
  src/test/java/seedu/address/logic/commands/FindByTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByTimeCommandParserTest.java
  src/test/java/seedu/address/model/reservation/TimeMatchesPredicateTest.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
Labels: priority.Medium

#202 Fix bug for mark and unmark command
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/testutil/TypicalReservations.java
Labels: alpha-bug

#228 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#229 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#232 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  preferences.json
Labels: alpha-bug

#218 Update listr
  src/main/java/seedu/address/model/ReservationsFilter.java
Labels: alpha-bug

#220 Change all instances of Person to Reservation
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/reservation/UniqueReservationList.java
  src/main/java/seedu/address/model/reservation/exceptions/DuplicateReservationException.java
  src/main/java/seedu/address/model/reservation/exceptions/ReservationNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/reservation/UniqueReservationListTest.java
Labels: alpha-bug

#242 Add Test Files
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReservationTest.java
Labels: priority.Medium

#359 Fix AddCommandParser
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: severity.Low, alpha-bug

#358 Fix Parser Util
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/reservation/Duration.java
  src/main/java/seedu/address/model/reservation/Name.java
  src/main/java/seedu/address/model/reservation/Pax.java
  src/main/java/seedu/address/model/reservation/Phone.java
  src/main/java/seedu/address/model/reservation/Remark.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/main/java/seedu/address/model/reservation/StartTime.java
  src/main/java/seedu/address/model/reservation/Table.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/reservation/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReservationTest.java
Labels: severity.Medium, alpha-bug
