Repository AY2425S2-CS2103T-T09-3/tp, pull requests merged in 2025-03, with the labels that each got.

#3 Add photo to docs/images
  docs/images/frozennfishh.png.jpg
Labels: type.Task, priority.Low

#5 AboutUs docs: Default document from template
  docs/AboutUs.md
Labels: type.Task, priority.Low

#29 Proposed edits to DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#37 DG Formatting and User Case updating
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Medium

#50 Remove Debugging Log
  src/main/java/seedu/address/ui/ReservationCard.java
Labels: type.Enhancement, priority.Low

#58 Update the check for duplication of reservations made
  src/main/java/seedu/address/model/reservation/Name.java
  src/main/java/seedu/address/model/reservation/Reservation.java
Labels: priority.Medium

#57 Add validation of day range
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/reservation/StartDate.java
Labels: priority.Medium

#56 Modify phone number validation
  src/main/java/seedu/address/model/reservation/Phone.java
Labels: priority.Medium

#55 Automate reservation id generation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/reservation/Phone.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/main/java/seedu/address/model/reservation/Table.java
Labels: priority.High

#64 Branch build fix
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditReservationDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/reservation/IdentificationTest.java
  src/test/java/seedu/address/model/reservation/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/reservation/PhoneTest.java
  src/test/java/seedu/address/model/reservation/ReservationTest.java
  src/test/java/seedu/address/model/reservation/StartDateTest.java
  src/test/java/seedu/address/model/reservation/UniqueReservationListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedReservationTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, severity.High

#74 Fix edit feature bugs.
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/reservation/StartDate.java
Labels: priority.High

#76 Add Command Enhancements
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/reservation/Identification.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedReservation.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/reservation/IdentificationTest.java
  src/test/java/seedu/address/model/reservation/StartDateTest.java
  src/test/java/seedu/address/testutil/EditReservationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
  src/test/java/seedu/address/testutil/TypicalReservations.java
Labels: type.Enhancement, priority.High, severity.Medium

#89 Incorporate ParseID check for Edit, Delete, Mark and Remark.
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reservation/Identification.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#94 Fix `isValidDate`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/reservation/Identification.java
  src/main/java/seedu/address/model/reservation/Reservation.java
  src/main/java/seedu/address/model/reservation/StartDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/ReservationCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Bug, priority.High, severity.High

#113 Append time to ID
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/reservation/Identification.java
  src/main/java/seedu/address/storage/JsonAdaptedReservation.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/reservation/IdentificationTest.java
  src/test/java/seedu/address/testutil/EditReservationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
Labels: priority.High, severity.Low

#122 Add colour change to ReservationCard based on `Regular` field
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PersonsList.java
  src/main/java/seedu/address/model/PersonsListManager.java
  src/main/java/seedu/address/model/reservation/Person.java
  src/main/java/seedu/address/ui/ReservationCard.java
  src/main/java/seedu/address/ui/ReservationListPanel.java
  src/main/resources/view/LightTheme.css
Labels: priority.Medium

#126 Update test case for mark command
  build.gradle
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
  src/test/java/seedu/address/testutil/TypicalReservations.java
Labels: priority.High

#133 Update unmarkCommandParser test cases
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: priority.Medium

#135 Fix Checkstyle Errors
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/PersonsList.java
  src/main/java/seedu/address/model/reservation/Name.java
  src/main/java/seedu/address/model/reservation/Phone.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
  src/test/java/seedu/address/testutil/TypicalReservations.java
Labels: priority.Medium

#138 Update EditCommandParserTest.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/reservation/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/ReservationBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalReservations.java
Labels: priority.Medium

#140 Fix UI Boot Issue
  src/main/java/seedu/address/model/reservation/Name.java
  src/main/java/seedu/address/model/reservation/Phone.java
Labels: priority.High

#148 Update build.gradle to enable assertions
  build.gradle
Labels: priority.Medium
